name: Publish

on:
  push:
    tags:        
      - '**'
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Prepare

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      
      - name: Build
        run: npm run build

      - name: Publish
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        
    
