name: Pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Build
        uses: npm run build

  checks:
    runs-on: ubuntu-latest
    name: Test and lint

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Lint
        uses: npm run lint
      - name: Test
        uses: npm run test