name: Pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare
        uses: ./prepare