name: Pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/workflows
          path: workflows

      - name: Prepare
        uses: ./workflows/.github/workflows/setup_base